//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetGestionHotel1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public client()
        {
            this.commentaire = new HashSet<commentaire>();
            this.reservation = new HashSet<reservation>();
        }
    
        public int id_client { get; set; }
        [Required(ErrorMessage ="field required"),MaxLength(10,ErrorMessage ="First name too long")]
        public string nom_client { get; set; }
        [Required(ErrorMessage = "field required"), MaxLength(10, ErrorMessage = "Last name too long")]
        public string prenom_client { get; set; }
        [Required(ErrorMessage = "field required"),EmailAddress(ErrorMessage ="Email Address invalid"), MaxLength(30, ErrorMessage = "Email Address too long")]
        public string email_client { get; set; }
        [Required(ErrorMessage = "field required"),Phone(ErrorMessage ="Phone number invalid"), MaxLength(10, ErrorMessage = "Phone number too long")]
        public string tel_client { get; set; }
        [Required(ErrorMessage = "field required"), MaxLength(10, ErrorMessage = "Login too long")]
        public string login_client { get; set; }
        [Required(ErrorMessage = "field required"),MinLength(4,ErrorMessage ="Password too short") ,MaxLength(10, ErrorMessage = "Password too long")]
        public string mdp_client { get; set; }
        [Compare("mdp_client",ErrorMessage ="Passwords don't match")]
        public string mdp_client2 { get; set; }
        public byte[] photo_profil { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<commentaire> commentaire { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reservation> reservation { get; set; }
    }
}
