//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetGestionHotel1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class commentaire
    {
        public int id_commentaire { get; set; }
        public int id_client { get; set; }
        public string text_commentaire { get; set; }
        public int score { get; set; }
        public string prediction { get; set; }
    
        public virtual client client { get; set; }
    }
}
