//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetGestionHotel1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gestion_hotelEntities : DbContext
    {
        public gestion_hotelEntities()
            : base("name=gestion_hotelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<administrateur> administrateur { get; set; }
        public virtual DbSet<categorie> categorie { get; set; }
        public virtual DbSet<chambre> chambre { get; set; }
        public virtual DbSet<client> client { get; set; }
        public virtual DbSet<commentaire> commentaire { get; set; }
        public virtual DbSet<images> images { get; set; }
        public virtual DbSet<reservation> reservation { get; set; }
    }
}
